--?? 1. Script Oracle 19c (XMLType)
CREATE TABLE MENSAJES_XML (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    MENSAJE XMLTYPE,
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

COMMIT;

/* ? 2. XML de ejemplo
<mensaje>
    <id>1</id>
    <usuario>Giovanny</usuario>
    <email>giovanny@email.com</email>
    <telefono>123456789</telefono>
    <ciudad>Armenia</ciudad>
    <pais>Colombia</pais>
    <descripcion>Prueba de almacenamiento XML en Oracle</descripcion>
</mensaje> */

--? 3. Inserción del XML en Oracle
INSERT INTO MENSAJES_XML (NOMBRE, MENSAJE)
VALUES (
    'Mensaje Prueba',
    XMLTYPE('
        <mensaje>
            <id>1</id>
            <usuario>Giovanny</usuario>
            <email>giovanny@email.com</email>
            <telefono>123456789</telefono>
            <ciudad>Armenia</ciudad>
            <pais>Colombia</pais>
            <descripcion>Prueba de almacenamiento XML en Oracle</descripcion>
        </mensaje>
    ')
);

COMMIT;

SELECT * FROM MENSAJES_XML;